CREATE TABLE CUSTUSER(
	ID VARCHAR2(50) PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(50) NOT NULL
)


SELECT * FROM custuser;


DELETE custuser
WHERE id='123';

UPDATE custuser 
set ID='123', ADDRESS='부천시'
WHERE name='일지매';