--TABLE 생성하기
CREATE TABLE TB_TEST01(
    COL_01 VARCHAR2(10),
    COL_02 VARCHAR2(10),
    COL_03 VARCHAR2(10),
    COL_04 VARCHAR2(10)
    );

CREATE TABLE TB_TEST02(
    COL_01 VARCHAR2(10),
    COL_02 VARCHAR2(10),
    COL_03 VARCHAR2(10),
    COL_04 VARCHAR2(10)
)
TABLESPACE TABLESPACE2;

--TABLE COPY (DATA 를 포함해서 복사한다.)
CREATE TABLE TB_TEST03
AS 
SELECT job_id AS "업무번호", job_title AS "업무명"  
FROM jobs;

SELECT * FROM TB_TEST03;
drop table TB_TEST03;

drop table TB_GROUP_DEPT;
CREATE TABLE TB_GROUP_DEPT
AS 
SELECT department_id AS "부서번호", SUM(salary) AS "합계", AVG(salary) AS "평균"
FROM employees
GROUP BY department_id;
SELECT * FROM TB_GROUP_DEPT;

--TABLE COPY :  데이터 미포함시키기
CREATE TABLE TB_TEST04
AS
SELECT * 
FROM departments
WHERE 1=2;       --1=2 성립할수 없는 조건을 WHERE에 넣으면 데이터를 미포함하게된다. 
select * FROM TB_test04;

--TABLE : CREATE, ALTER, DROP (생성 , 수정, 삭제, 
--DATA : INSERT, UPDATE, DELETE, SELECT (추가, 업데이트 삭제 선택)

--TABLE 수정 : 테이블명 수정. 
ALTER TABLE TB_TEST04
RENAME TO TB_TEST99;

SELECT * FROM TB_TEST99;

--TABLE 수정 : 단일컬럼 추가
ALTER TABLE TB_TEST99
ADD 
LOCATION_NAME VARCHAR2(30);

--TABLE 수정 : 다중컬럼 추가
ALTER TABLE TB_TEST99
ADD
(COL_01 VARCHAR2(30), COL_02 NUMBER(5,2));

-- TABLE 수정 : 단일컬럼 수정
ALTER TABLE TB_TEST99
MODIFY
COL_01 VARCHAR2(20);

-- TABLE 수정 : 다중컬럼 수정
ALTER TABLE TB_TEST99
MODIFY
(COL_01 VARCHAR2(20), COL_02 NUMBER(4));



--TABLE 수정 : 컬럼 삭제
ALTER TABLE TB_TEST99
DROP COLUMN LOCATION_NAME;

--TABLE 수정 : 컬럼 다중 삭제
ALTER TABLE TB_TEST99
DROP
(COL_01, COL_02);


--TABLE 수정 : 컬럼명 수정
ALTER TABLE TB_TEST99
RENAME
COLUMN DEPARTMENT_ID TO "부서번호";

DROP TABLE TB_TEST01;

DROP TABLE TB_TEST02
CASCADE CONSTRAINTS;    --제약조건까지 삭제해주는 명령어이다. 
--삭제된 테이블을 복구
FLASHBACK TABLE TB_TEST02
TO BEFORE DROP;

PURGE RECYCLEBIN;   --휴지통 비우기


DROP TABLE TB_TEST03;
DROP TABLE TB_TEST99;








