DROP TABLE BBS
CASCADE CONSTRAINTs;

DROP SEQUENCE SEQ_BBS;

CREATE TABLE BBS(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(400) NOT NULL,
	WDATE DATE NOT NULL,
	DEL NUMBER(1) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;

ALTER TABLE BBS 
ADD CONSTRAINT FK_BBS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM BBS;

INSERT INTO BBS VALUES(SEQ_BBS.nextval, 'asd', 'hello', 'Hello content', sysdate, 0, 0);


SELECT READCOUNT 
FROM BBS 
WHERE SEQ = 5 
AND TITLE ='hello'  AND CONTENT = 'Hello content';
		
		
		
		